apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  ports:
  - port: 30000
    protocol: TCP
    name: ftps
  - port: 21
    protocol: TCP
    name: my-ftps
  selector:
    run: ftps

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    run: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ftps
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: rzafari
              key: user
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rzafari
              key: password
        ports:
        - containerPort: 21
        - containerPort: 30000