apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  ports:
  - port: 30000
    protocol: TCP
    name: ftps
  - port: 21
    protocol: TCP
    name: my-ftps
  selector:
    app: ftps

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000