apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    run: ftps
spec:
  type: LoadBalancer
  ports:
  - port: 30000
    protocol: TCP
    name: ftps
  - port: 21
    protocol: TCP
    name: my-ftps
  selector:
    run: ftps

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    run: ftps
  name: ftps-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    run: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ftps
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000
        volumeMounts:
        - name: ftps-persitent-storage
          mountPath: var/lib/ftps
      volumes:
      - name: ftps-persitent-storage
        persistentVolumeClaim:
          claimName: ftps-pvc
