apiVersion: v1
kind: Service
metadata:
  labels:
    run: grafana
  name: grafana-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    run: grafana

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-deployment
  labels:
    run: grafana
spec:
  serviceName: grafana
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-img
        imagePullPolicy: Never
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: rzafari
              key: user
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rzafari
              key: password
        ports:
        - containerPort: 3000 