apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    run: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    name: http
  selector:
    run: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    run: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    run: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-img
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: host
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
