apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadate:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql-image
          imagePullPolicy: Never
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: host 
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: name 
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: password
          ports:
          - containerPort: 3306
            name: mysql
          VolumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-volumeclaim
