apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
  name: mysql-volumeclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-img
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: host 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: name 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-volumeclaim
