apiVersion: v1
kind: Service
metadata:
 labels:
   app: nginx
 name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    protocol: TCP
  - port: 443
    name: https
    targetPort: 443
    protocol: TCP

---

apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-img
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
