apiVersion: v1
kind: service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  ports:
  - name: phpmyadmin
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchlabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin-image
          imagePullPolicy: Never
          env:
          - name: WP_DB_HOST
            valueFrom:
             secretKeyRef:
               name: wp-secret
               key: host 
          - name: WP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: name 
          - name: WP_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: user
          - name: WP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: password
         ports:
         - containerPort: 5000
           name: phpmyadmin
