apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    run: phpmyadmin
spec:
  selector:
    run: phpmyadmin
  type: LoadBalancer
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    run: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      run: phpmyadmin
  template:
    metadata:
      labels:
        run: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-img
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: password
        ports:
        - containerPort: 5000
