apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress-service
spec:
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  selector:
    app: wordpress

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volumeclaim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: wordpress-deployment
    labels:
      app: wordpress
spec:
  serviceName: wordpress
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: host 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: name 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: password
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-volumeclaim
