apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    run: wordpress
spec:
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  selector:
    run: wordpress

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  labels:
    run: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    run: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wordpress
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-id-user
              key: host
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc
      