apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress-service
spec:
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-deployment
    labels:
        app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: alpine-linux
          imagePullPolicy: Never
          env:
          - name: WP_DB_HOST
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: host 
          - name: WP_DB_NAME
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: name 
          - name: WP_DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-user
                key: user
          - name: WP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-password
                key: password
          ports:
            - containerPport: 5050
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountpath: var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim
