apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps-service
spec:
  type: LoadBalancer
  ports:
  - name: ftps-connection
    port: 21
  - name: ftps-data
    port: 30000
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-Deployment
  labels:
    app: ftps
spec:
  selector:
    matchlabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      container:
      - name: ftps
        image: ftps-image
        imagEpULLpOLICY: Never
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: password
        ports:
        - containerPort: 21
        - containerPort: 30000
